// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as AgendamentoRouteImport } from './routes/agendamento'
import { Route as BarbeirosRouteImport } from './routes/barbeiros'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as GaleriaRouteImport } from './routes/galeria'
import { Route as PlanosRouteImport } from './routes/planos'
import { Route as ProdutosRouteImport } from './routes/produtos'
import { Route as ServicosRouteImport } from './routes/servicos'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendamentoRoute = AgendamentoRouteImport.update({
  id: '/agendamento',
  path: '/agendamento',
  getParentRoute: () => rootRouteImport,
} as any)
const BarbeirosRoute = BarbeirosRouteImport.update({
  id: '/barbeiros',
  path: '/barbeiros',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriaRoute = GaleriaRouteImport.update({
  id: '/galeria',
  path: '/galeria',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanosRoute = PlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosRoute = ProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosRoute = ServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/agenda': typeof AgendaRoute
  '/agendamento': typeof AgendamentoRoute
  '/barbeiros': typeof BarbeirosRoute
  '/contato': typeof ContatoRoute
  '/galeria': typeof GaleriaRoute
  '/planos': typeof PlanosRoute
  '/produtos': typeof ProdutosRoute
  '/servicos': typeof ServicosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/agenda': typeof AgendaRoute
  '/agendamento': typeof AgendamentoRoute
  '/barbeiros': typeof BarbeirosRoute
  '/contato': typeof ContatoRoute
  '/galeria': typeof GaleriaRoute
  '/planos': typeof PlanosRoute
  '/produtos': typeof ProdutosRoute
  '/servicos': typeof ServicosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/agenda': typeof AgendaRoute
  '/agendamento': typeof AgendamentoRoute
  '/barbeiros': typeof BarbeirosRoute
  '/contato': typeof ContatoRoute
  '/galeria': typeof GaleriaRoute
  '/planos': typeof PlanosRoute
  '/produtos': typeof ProdutosRoute
  '/servicos': typeof ServicosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/agenda'
    | '/agendamento'
    | '/barbeiros'
    | '/contato'
    | '/galeria'
    | '/planos'
    | '/produtos'
    | '/servicos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/agenda'
    | '/agendamento'
    | '/barbeiros'
    | '/contato'
    | '/galeria'
    | '/planos'
    | '/produtos'
    | '/servicos'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/agenda'
    | '/agendamento'
    | '/barbeiros'
    | '/contato'
    | '/galeria'
    | '/planos'
    | '/produtos'
    | '/servicos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AgendaRoute: typeof AgendaRoute
  AgendamentoRoute: typeof AgendamentoRoute
  BarbeirosRoute: typeof BarbeirosRoute
  ContatoRoute: typeof ContatoRoute
  GaleriaRoute: typeof GaleriaRoute
  PlanosRoute: typeof PlanosRoute
  ProdutosRoute: typeof ProdutosRoute
  ServicosRoute: typeof ServicosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agendamento': {
      id: '/agendamento'
      path: '/agendamento'
      fullPath: '/agendamento'
      preLoaderRoute: typeof AgendamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/barbeiros': {
      id: '/barbeiros'
      path: '/barbeiros'
      fullPath: '/barbeiros'
      preLoaderRoute: typeof BarbeirosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeria': {
      id: '/galeria'
      path: '/galeria'
      fullPath: '/galeria'
      preLoaderRoute: typeof GaleriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planos': {
      id: '/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof PlanosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos': {
      id: '/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof ProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos': {
      id: '/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof ServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AgendaRoute: AgendaRoute,
  AgendamentoRoute: AgendamentoRoute,
  BarbeirosRoute: BarbeirosRoute,
  ContatoRoute: ContatoRoute,
  GaleriaRoute: GaleriaRoute,
  PlanosRoute: PlanosRoute,
  ProdutosRoute: ProdutosRoute,
  ServicosRoute: ServicosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
